language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
    include:
        - php: 5.3
          env: dependencies=lowest

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar --dev install
    - if [ "$dependencies" = "lowest"]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
