language: php

php:
    - 5.3
    - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar --dev install

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover -c tests/
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
